twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_version: '%app_version%'
        locales: '%app_locales%'
        locale: '%locale%'

when@test:
    twig:
        strict_variables: true
