name: "Lint"

on:
  pull_request:
  push:
    branches:
      - master
      - '*.x'

env:
  fail-fast: true

jobs:

  linters:
    name: Linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.2']

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@2.7.0
        with:
          coverage: "none"
          extensions: intl
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: "Set composer cache directory"
        id: cache-vendor
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

      - name: "Composer install"
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: composer install --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install PHPUnit
        id: install
        run: vendor/bin/simple-phpunit install

      - name: PHP-CS-Fixer
        if: always() && steps.install.outcome == 'success'
        run: vendor/bin/php-cs-fixer fix --diff --dry-run --ansi

      - name: PHPStan
        if: always() && steps.install.outcome == 'success'
        run: vendor/bin/phpstan analyse

      - name: Rector
        if: always() && steps.install.outcome == 'success'
        run: vendor/bin/rector process --ansi

      - name: Lint YAML files
        if: always() && steps.install.outcome == 'success'
        run: ./bin/console lint:yaml config --parse-tags --ansi

      - name: Lint Twig templates
        if: always() && steps.install.outcome == 'success'
        run: ./bin/console lint:twig templates --env=prod --ansi

      - name: Lint XLIFF translations
        if: always() && steps.install.outcome == 'success'
        run: ./bin/console lint:xliff translations --ansi

      - name: Lint Parameters and Services
        if: always() && steps.install.outcome == 'success'
        run: ./bin/console lint:container --no-debug --ansi

      - name: Lint Doctrine entities
        if: always() && steps.install.outcome == 'success'
        run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction --ansi

      - name: Lint Composer config
        if: always() && steps.install.outcome == 'success'
        run: composer validate --strict --ansi

      - name: Check if any dependencies are compromised
        if: always() && steps.install.outcome == 'success'
        run: composer audit --ansi
